# Generated by Django 5.2 on 2025-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacidade', models.PositiveIntegerField(default=4)),
                ('localizacao', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Reservada', 'Reservada'), ('Ocupada', 'Ocupada')], default='Disponível', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
