# Generated by Django 5.2 on 2025-05-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='atualizado_em',
            new_name='atualizada_em',
        ),
        migrations.RenameField(
            model_name='mesa',
            old_name='criado_em',
            new_name='criada_em',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='localizacao',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='livre', max_length=10),
        ),
    ]
