# Generated by Django 5.2 on 2025-05-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidade', models.CharField(default='unid', max_length=20)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('Baixo', 'Baixo'), ('Alto', 'Alto')], default='OK', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
