# Generated by Django 5.2 on 2025-04-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_abertura', models.TimeField()),
                ('hora_fechamento', models.TimeField()),
                ('tipo', models.CharField(choices=[('Regular', 'Regular'), ('Feriado', 'Feriado'), ('Evento', 'Evento')], default='Regular', max_length=20)),
                ('data_especifica', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
